import { StyleSheet } from "react-native";

export default StyleSheet.create({
  selectionToolbar: { flexDirection: "row", flexWrap: "wrap", alignItems: "center", paddingHorizontal: 10 },
  selectionButton: { paddingHorizontal: 9, paddingVertical: 13 },
  selectionBadge: { position: "absolute", top: 7, left: 7, backgroundColor: "#0008", borderRadius: 14 },
  disabledAction: { opacity: 0.4 },
  dangerText: { color: "#ff6868", fontSize: 13, fontWeight: "700" },
  viewerOperation: { position: "absolute", left: 12, right: 12, zIndex: 6, backgroundColor: "#161616", borderRadius: 12 },
  primaryPhotoActionText: { color: "#171717", fontSize: 14, fontWeight: "600", flex: 1 },
  infoHeaderCopy: { flex: 1 },
  infoSubtitle: { color: "#9d9d9d", fontSize: 12, marginTop: 7 },
  captureMetrics: { flexDirection: "row", backgroundColor: "#232323", borderRadius: 18, paddingVertical: 20, marginBottom: 6 },
  captureMetric: { flex: 1, paddingHorizontal: 12, justifyContent: "center" },
  captureMetricDivider: { borderLeftWidth: 1, borderLeftColor: "rgba(255,255,255,0.09)" },
  captureMetricLabel: { color: "#ababab", fontSize: 10, marginBottom: 8 },
  captureMetricValue: { color: "#f3f3f3", fontSize: 23, fontWeight: "500", letterSpacing: -0.6, fontVariant: ["tabular-nums"] },
  actionIcon: { width: 36, height: 36, borderRadius: 12, backgroundColor: "rgba(255,255,255,0.045)", alignItems: "center", justifyContent: "center" },
  actionCopy: { flex: 1, gap: 4 },
  actionSubtitle: { color: "#999999", fontSize: 11, lineHeight: 16 },
  projectActionText: { color: "#ffaa00", fontSize: 13, fontWeight: "500" },
  copyOption: { paddingVertical: 4, borderTopWidth: 1, borderTopColor: "rgba(255,255,255,0.07)" },
  actionRow: { flexDirection: "row", alignItems: "center", gap: 12, minHeight: 64, paddingVertical: 16 },
  primaryPhotoAction: { flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 10, backgroundColor: "#ffaa00", borderRadius: 16, minHeight: 54, paddingHorizontal: 18, marginBottom: 4 },
  infoSectionLabel: { color: "#969696", fontSize: 10, fontWeight: "600", letterSpacing: 1.8, marginTop: 28, marginBottom: 12, marginLeft: 2 },
  photoActionGroup: { backgroundColor: "#1c1c1c", borderColor: "rgba(255,255,255,0.055)", borderWidth: 1, borderRadius: 20, paddingHorizontal: 16, paddingVertical: 2 },
  actionLabel: { color: "#eeeeee", fontSize: 14, fontWeight: "500", flexShrink: 1, lineHeight: 20 },
  actionDivider: { borderTopWidth: 1, borderTopColor: "rgba(255,255,255,0.07)" },
  deletePhotoButton: { flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 8, marginTop: 28, minHeight: 52, padding: 14, borderRadius: 16, backgroundColor: "rgba(221,110,104,0.055)" },
  actionExplanation: { color: "#a5a5a5", fontSize: 12, lineHeight: 18, marginBottom: 16 },
  operationProgress: { flexDirection: "row", alignItems: "center", flexWrap: "wrap", gap: 8, padding: 12 },
  operationText: { color: "#ddd", flexShrink: 1, fontSize: 13 },
  batchModalBackdrop: { flex: 1, backgroundColor: "#000a", justifyContent: "center", padding: 24 },
  batchModalContent: { backgroundColor: "#161616", borderRadius: 24, padding: 20, gap: 18 },
  ratingBadge: {
    position: "absolute",
    bottom: 4,
    right: 4,
    flexDirection: "row",
    gap: 3,
    alignItems: "center",
    backgroundColor: "#000b",
    borderRadius: 5,
    paddingHorizontal: 5,
    paddingVertical: 2,
  },
  ratingBadgeText: { color: "#fff", fontSize: 12 },
  ratingSection: { paddingTop: 16, paddingBottom: 16 },
  ratingLabel: { color: "#bdbdbd", fontSize: 12, fontWeight: "500", marginBottom: 12 },
  ratingControls: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", maxWidth: 340 },
  ratingStar: { padding: 6, minWidth: 36, flexShrink: 1, minHeight: 44, alignItems: "center", justifyContent: "center" },
  ratingClear: { padding: 6, minWidth: 36, flexShrink: 1, minHeight: 44, alignItems: "center", justifyContent: "center", marginRight: 4 },
  container: { flex: 1, backgroundColor: "#000" },
  loadingContent: { flex: 1 },
  listContent: {
    flexGrow: 1,
    paddingBottom: 32,
    paddingHorizontal: 14,
    paddingTop: 12,
  },
  sectionTitle: {
    color: "#a7a7a7",
    fontSize: 17,
    fontWeight: "600",
    marginBottom: 12,
    marginTop: 15,
  },
  photoRow: { flexDirection: "row", gap: 7, marginBottom: 7 },
  photoItem: { flex: 1 },
  photoPlaceholder: { flex: 1 },
  image: {
    aspectRatio: 0.76,
    backgroundColor: "#151515",
    borderRadius: 19,
    width: "100%",
  },
  permissionContainer: {
    alignItems: "center",
    backgroundColor: "#000",
    flex: 1,
    justifyContent: "center",
    paddingHorizontal: 32,
  },
  permissionText: {
    color: "#f5f5f5",
    fontSize: 16,
    lineHeight: 23,
    marginTop: 16,
    textAlign: "center",
  },
  permissionButton: {
    backgroundColor: "#f5f5f5",
    borderRadius: 999,
    marginTop: 18,
    paddingHorizontal: 20,
    paddingVertical: 11,
  },
  permissionButtonText: { color: "#111", fontSize: 15, fontWeight: "600" },
  emptyContainer: {
    alignItems: "center",
    flex: 1,
    justifyContent: "center",
    paddingBottom: 80,
    paddingHorizontal: 24,
  },
  emptyTitle: {
    color: "#f5f5f5",
    fontSize: 18,
    fontWeight: "600",
    marginBottom: 7,
  },
  emptyText: {
    color: "#8c8c8c",
    fontSize: 15,
    lineHeight: 21,
    textAlign: "center",
  },
  viewer: { backgroundColor: "transparent", flex: 1 },
  viewerContent: { flex: 1, zIndex: 2 },
  viewerTransitionBackdrop: {
    backgroundColor: "#000",
    bottom: 0,
    left: 0,
    position: "absolute",
    right: 0,
    top: 0,
    zIndex: 1,
  },
  viewerTransitionImage: {
    backgroundColor: "#000",
    overflow: "hidden",
    position: "absolute",
    zIndex: 20,
  },
  viewerTopBar: {
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "space-between",
    left: 0,
    paddingBottom: 10,
    paddingHorizontal: 16,
    position: "absolute",
    right: 0,
    top: 0,
    zIndex: 5,
  },
  viewerRoundButton: {
    alignItems: "center",
    backgroundColor: "rgba(255,255,255,0.09)",
    borderColor: "rgba(255,255,255,0.09)",
    borderRadius: 22,
    borderWidth: 1,
    height: 42,
    justifyContent: "center",
    width: 42,
  },
  viewerHeading: { alignItems: "center", flex: 1, paddingHorizontal: 12 },
  viewerDate: { color: "#fff", fontSize: 14, fontWeight: "600" },
  viewerCounter: {
    color: "rgba(255,255,255,0.42)",
    fontSize: 11,
    marginTop: 3,
  },
  viewerGestureArea: { flex: 1, paddingBottom: 154, paddingTop: 80 },
  viewerPhotoPage: { flex: 1, paddingHorizontal: 12, paddingVertical: 12 },
  viewerPhotoFrame: {
    backgroundColor: "#000",
    borderColor: "rgba(255,255,255,0.07)",
    borderRadius: 28,
    borderWidth: 1,
    flex: 1,
    overflow: "hidden",
  },
  viewerPhoto: { height: "100%", width: "100%" },
  viewerBottom: {
    alignItems: "center",
    backgroundColor: "#000",
    bottom: 0,
    left: 0,
    paddingTop: 2,
    position: "absolute",
    right: 0,
  },
  infoHandleButton: { alignItems: "center", paddingBottom: 8, width: "100%" },
  infoHandle: {
    backgroundColor: "rgba(255,255,255,0.22)",
    borderRadius: 2,
    height: 3,
    marginBottom: 5,
    width: 34,
  },
  infoButtonContent: { alignItems: "center", flexDirection: "row", gap: 4 },
  infoButtonText: { color: "#ffaa00", fontSize: 12, fontWeight: "600" },
  thumbnailList: { gap: 7, paddingHorizontal: 16, paddingVertical: 2 },
  thumbnailButton: {
    borderColor: "transparent",
    borderRadius: 13,
    borderWidth: 2,
    height: 58,
    opacity: 0.48,
    overflow: "hidden",
    padding: 2,
    width: 51,
  },
  thumbnailButtonActive: {
    borderColor: "#ffaa00",
    opacity: 1,
    transform: [{ scale: 1.04 }],
  },
  thumbnailImage: { borderRadius: 9, height: "100%", width: "100%" },
  infoBackdrop: {
    backgroundColor: "rgba(0,0,0,0.22)",
    bottom: 0,
    left: 0,
    position: "absolute",
    right: 0,
    top: 0,
    zIndex: 10,
  },
  infoBackdropPressable: { flex: 1 },
  infoPanel: { bottom: 0, left: 0, maxHeight: "66%", position: "absolute", right: 0, zIndex: 11 },
  infoPanelBlur: { backgroundColor: "rgba(19,19,19,0.97)", borderColor: "rgba(255,255,255,0.09)", borderTopLeftRadius: 32, borderTopRightRadius: 32, borderWidth: 1, maxHeight: "100%", overflow: "hidden", paddingTop: 10 },
  infoPanelHandle: {
    alignSelf: "center",
    backgroundColor: "rgba(255,255,255,0.22)",
    borderRadius: 3,
    height: 4,
    width: 38,
  },
  infoHeader: { alignItems: "center", flexDirection: "row", justifyContent: "space-between", gap: 12, paddingHorizontal: 24, paddingTop: 20, paddingBottom: 24 },
  infoEyebrow: { color: "#ffaa00", fontSize: 9, fontWeight: "600", letterSpacing: 2.2, marginBottom: 8 },
  infoTitle: { color: "#f3f3f3", fontSize: 26, fontWeight: "600", letterSpacing: -0.8 },
  infoCloseButton: { alignItems: "center", backgroundColor: "rgba(255,255,255,0.055)", borderRadius: 22, height: 44, justifyContent: "center", width: 44, flexShrink: 0 },
  infoScrollContent: { paddingHorizontal: 24 },
  photoDataLoading: {
    alignItems: "center",
    justifyContent: "center",
    padding: 45,
  },
  loadingText: { color: "rgba(255,255,255,0.5)", fontSize: 13, marginTop: 10 },
  badgeContainer: { flexDirection: "row", flexWrap: "wrap", gap: 6, marginBottom: 14 },
  badge: { backgroundColor: "rgba(255,170,0,0.07)", borderRadius: 6, paddingHorizontal: 9, paddingVertical: 5 },
  badgeText: { color: "#ffaa00", fontSize: 10, fontWeight: "500", letterSpacing: 0.3 },
  intelligentTagsSection: { backgroundColor: "#1c1c1c", borderColor: "rgba(255,255,255,0.055)", borderRadius: 16, borderWidth: 1, marginBottom: 14, overflow: "hidden" },
  intelligentTagsHeader: {
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "space-between",
    paddingHorizontal: 14,
    paddingVertical: 13,
  },
  intelligentTagsTitleRow: {
    alignItems: "center",
    flexDirection: "row",
    gap: 8,
  },
  intelligentTagsTitle: { color: "#fff", fontSize: 14, fontWeight: "600" },
  intelligentTagsCount: { alignItems: "center", backgroundColor: "rgba(255,255,255,0.06)", borderRadius: 7, justifyContent: "center", minWidth: 22, paddingHorizontal: 6, paddingVertical: 2 },
  intelligentTagsCountText: { color: "#bfbfbf", fontSize: 10, fontWeight: "600" },
  intelligentTagsChips: {
    borderTopColor: "rgba(255,255,255,0.06)",
    borderTopWidth: 1,
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 7,
    padding: 12,
  },
  intelligentTagChip: { backgroundColor: "rgba(255,255,255,0.045)", borderRadius: 8, paddingHorizontal: 10, paddingVertical: 6 },
  intelligentTagText: { color: "#d2d2d2", fontSize: 12, fontWeight: "400" },
  exifContainer: { flexDirection: "row", flexWrap: "wrap", justifyContent: "space-between", paddingTop: 6 },
  exifItemWrapper: { paddingVertical: 12, borderBottomWidth: 1, borderBottomColor: "rgba(255,255,255,0.065)", width: "48%" },
  exifItemWide: { width: "100%" },
  mapContainer: {
    borderRadius: 18,
    marginTop: 12,
    overflow: "hidden",
    width: "100%",
  },
  noMetadataText: {
    color: "rgba(255,255,255,0.5)",
    fontSize: 14,
    paddingHorizontal: 4,
    paddingVertical: 24,
    textAlign: "center",
  },
  infoActionButton: { alignItems: "flex-start", borderTopColor: "rgba(255,255,255,0.07)", borderTopWidth: 1, justifyContent: "center", minHeight: 54 },
  infoActionText: { color: "#ffaa00", fontSize: 13, fontWeight: "700" },
});
