import { StyleSheet } from "react-native";

export default StyleSheet.create({
  container: { flex: 1, backgroundColor: "#000" },
  navigationBar: {
    alignItems: "center",
    backgroundColor: "rgba(0,0,0,0.88)",
    borderBottomWidth: 1,
    flexDirection: "row",
    justifyContent: "center",
    left: 0,
    paddingHorizontal: 14,
    position: "absolute",
    right: 0,
    top: 0,
    zIndex: 10,
  },
  title: { color: "#fff", fontSize: 18, fontWeight: "600", marginLeft: 20, textAlign: "center" },
  navigationProjectSelector: { marginLeft: "auto" },
  listContent: { flexGrow: 1, paddingBottom: 32, paddingHorizontal: 14, paddingTop: 40 },
  sectionTitle: {
    color: "#a7a7a7",
    fontSize: 17,
    fontWeight: "600",
    marginBottom: 12,
    marginTop: 15,
  },
  photoRow: { flexDirection: "row", gap: 7, marginBottom: 7 },
  photoItem: { flex: 1 },
  photoPlaceholder: { flex: 1 },
  image: { aspectRatio: 0.76, backgroundColor: "#151515", borderRadius: 19, width: "100%" },
  permissionContainer: {
    alignItems: "center",
    backgroundColor: "#000",
    flex: 1,
    justifyContent: "center",
    paddingHorizontal: 32,
  },
  permissionText: { color: "#f5f5f5", fontSize: 16, lineHeight: 23, marginTop: 16, textAlign: "center" },
  permissionButton: { backgroundColor: "#f5f5f5", borderRadius: 999, marginTop: 18, paddingHorizontal: 20, paddingVertical: 11 },
  permissionButtonText: { color: "#111", fontSize: 15, fontWeight: "600" },
  emptyContainer: { alignItems: "center", flex: 1, justifyContent: "center", paddingBottom: 80, paddingHorizontal: 24 },
  emptyTitle: { color: "#f5f5f5", fontSize: 18, fontWeight: "600", marginBottom: 7 },
  emptyText: { color: "#8c8c8c", fontSize: 15, lineHeight: 21, textAlign: "center" },
  viewer: { backgroundColor: "transparent", flex: 1 },
  viewerContent: { flex: 1, zIndex: 2 },
  viewerTransitionBackdrop: {
    backgroundColor: "#050505",
    bottom: 0,
    left: 0,
    position: "absolute",
    right: 0,
    top: 0,
    zIndex: 1,
  },
  viewerTransitionImage: {
    backgroundColor: "#0c0c0c",
    overflow: "hidden",
    position: "absolute",
    zIndex: 20,
  },
  viewerTopBar: {
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "space-between",
    left: 0,
    paddingBottom: 10,
    paddingHorizontal: 16,
    position: "absolute",
    right: 0,
    top: 0,
    zIndex: 5,
  },
  viewerRoundButton: {
    alignItems: "center",
    backgroundColor: "rgba(255,255,255,0.09)",
    borderColor: "rgba(255,255,255,0.09)",
    borderRadius: 22,
    borderWidth: 1,
    height: 42,
    justifyContent: "center",
    width: 42,
  },
  viewerHeading: { alignItems: "center", flex: 1, paddingHorizontal: 12 },
  viewerDate: { color: "#fff", fontSize: 14, fontWeight: "600" },
  viewerCounter: { color: "rgba(255,255,255,0.42)", fontSize: 11, marginTop: 3 },
  viewerGestureArea: { flex: 1, paddingBottom: 154, paddingTop: 80 },
  viewerPhotoPage: { flex: 1, paddingHorizontal: 12, paddingVertical: 12 },
  viewerPhotoFrame: {
    backgroundColor: "#0c0c0c",
    borderColor: "rgba(255,255,255,0.07)",
    borderRadius: 28,
    borderWidth: 1,
    flex: 1,
    overflow: "hidden",
  },
  viewerPhoto: { height: "100%", width: "100%" },
  viewerBottom: {
    alignItems: "center",
    backgroundColor: "#050505",
    bottom: 0,
    left: 0,
    paddingTop: 2,
    position: "absolute",
    right: 0,
  },
  infoHandleButton: { alignItems: "center", paddingBottom: 8, width: "100%" },
  infoHandle: { backgroundColor: "rgba(255,255,255,0.22)", borderRadius: 2, height: 3, marginBottom: 5, width: 34 },
  infoButtonContent: { alignItems: "center", flexDirection: "row", gap: 4 },
  infoButtonText: { color: "#ffaa00", fontSize: 12, fontWeight: "600" },
  thumbnailList: { gap: 7, paddingHorizontal: 16, paddingVertical: 2 },
  thumbnailButton: {
    borderColor: "transparent",
    borderRadius: 13,
    borderWidth: 2,
    height: 58,
    opacity: 0.48,
    overflow: "hidden",
    padding: 2,
    width: 51,
  },
  thumbnailButtonActive: { borderColor: "#ffaa00", opacity: 1, transform: [{ scale: 1.04 }] },
  thumbnailImage: { borderRadius: 9, height: "100%", width: "100%" },
  infoBackdrop: {
    backgroundColor: "rgba(0,0,0,0.22)",
    bottom: 0,
    left: 0,
    position: "absolute",
    right: 0,
    top: 0,
    zIndex: 10,
  },
  infoBackdropPressable: { flex: 1 },
  infoPanel: { bottom: 0, left: 0, maxHeight: "58%", position: "absolute", right: 0, zIndex: 11 },
  infoPanelBlur: {
    backgroundColor: "rgba(16,16,16,0.96)",
    borderColor: "rgba(255,255,255,0.1)",
    borderTopLeftRadius: 30,
    borderTopRightRadius: 30,
    borderWidth: 1,
    maxHeight: "100%",
    overflow: "hidden",
    paddingTop: 10,
  },
  infoPanelHandle: { alignSelf: "center", backgroundColor: "rgba(255,255,255,0.22)", borderRadius: 3, height: 4, width: 38 },
  infoHeader: { alignItems: "center", flexDirection: "row", justifyContent: "space-between", paddingHorizontal: 20, paddingVertical: 14 },
  infoEyebrow: { color: "#ffaa00", fontSize: 10, fontWeight: "700", letterSpacing: 1.4, marginBottom: 3 },
  infoTitle: { color: "#fff", fontSize: 24, fontWeight: "700" },
  infoCloseButton: { alignItems: "center", backgroundColor: "rgba(255,255,255,0.09)", borderRadius: 18, height: 36, justifyContent: "center", width: 36 },
  infoScrollContent: { paddingBottom: 12, paddingHorizontal: 16 },
  photoDataLoading: { alignItems: "center", justifyContent: "center", padding: 45 },
  loadingText: { color: "rgba(255,255,255,0.5)", fontSize: 13, marginTop: 10 },
  badgeContainer: { flexDirection: "row", flexWrap: "wrap", gap: 6, marginBottom: 10 },
  badge: {
    backgroundColor: "rgba(255,170,0,0.08)",
    borderColor: "rgba(255,170,0,0.18)",
    borderRadius: 999,
    borderWidth: 1,
    paddingHorizontal: 10,
    paddingVertical: 5,
  },
  badgeText: { color: "#ffc14d", fontSize: 11, fontWeight: "600" },
  exifContainer: {
    backgroundColor: "rgba(255,255,255,0.045)",
    borderColor: "rgba(255,255,255,0.07)",
    borderRadius: 18,
    borderWidth: 1,
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-between",
    paddingHorizontal: 14,
    paddingTop: 14,
  },
  exifItemWrapper: { marginBottom: 8, width: "49%" },
  exifItemWide: { width: "100%" },
  mapContainer: { borderRadius: 18, marginTop: 12, overflow: "hidden", width: "100%" },
  noMetadataText: { color: "rgba(255,255,255,0.5)", fontSize: 14, paddingHorizontal: 4, paddingVertical: 24, textAlign: "center" },
  infoActions: { flexDirection: "row", gap: 8, marginTop: 12 },
  infoActionButton: {
    alignItems: "center",
    backgroundColor: "rgba(255,170,0,0.07)",
    borderColor: "rgba(255,170,0,0.18)",
    borderRadius: 13,
    borderWidth: 1,
    flex: 1,
    justifyContent: "center",
    minHeight: 46,
    paddingHorizontal: 12,
  },
  infoActionText: { color: "#ffaa00", fontSize: 13, fontWeight: "700" },
  infoActionDanger: {
    alignItems: "center",
    backgroundColor: "rgba(255,68,68,0.07)",
    borderColor: "rgba(255,68,68,0.17)",
    borderRadius: 13,
    borderWidth: 1,
    height: 46,
    justifyContent: "center",
    width: 48,
  },
});
