import { StyleSheet } from "react-native";

export default StyleSheet.create({
  container: {
    position: "absolute",
    bottom: -30,
    left: 0,
    right: 0,
  },
  selectorSection: {
    width: "100%",
  },
  compactSection: {
    marginTop: 10,
  },
  effectsArea: {
    width: "100%",
    flexDirection: "row",
    alignItems: "center",
  },
  effectsColumn: {
    flex: 1,
    minWidth: 0,
    marginRight: 48,
    overflow: "hidden",
  },
  quickShutterSlot: {
    width: 76,
    flexShrink: 0,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 12,
  },
  sectionTitle: {
    color: "#fff",
    fontSize: 13,
    fontWeight: "600",
    paddingHorizontal: 16,
    marginBottom: 2,
    display: "none",
  },
  header: {
    padding: 10,
    // borderBottomWidth: 1,
    // borderBottomColor: "#333",
  },
  title: {
    color: "#fff",
    fontSize: 18,
    fontWeight: "600",
    textAlign: "center",
  },
  scrollContent: {
    paddingHorizontal: 16,
    paddingTop: 6,
    paddingBottom: 12,
    gap: 8,
  },
  compactScrollContent: {
    paddingLeft: 16,
    paddingRight: 40,
    paddingTop: 2,
    paddingBottom: 4,
    gap: 4,
  },
  compactScrollViewport: {
    position: "relative",
    overflow: "hidden",
  },
  scrollEndFade: {
    position: "absolute",
    top: 0,
    right: 0,
    bottom: 0,
    width: 32,
  },
  effectButton: {
    alignItems: "center",
    width: 58,
  },
  effectButtonSelected: {},
  polaroidButton: {
    padding: 2,
  },
  polaroidButtonSelected: {
    transform: [{ translateY: -2 }],
  },
  polaroid: {
    width: 64,
    height: 76,
    paddingTop: 1,
    paddingHorizontal: 1,
    paddingBottom: 0,
    backgroundColor: "#f7f4ec",
    borderRadius: 2,
    borderWidth: 2,
    borderColor: "rgba(255,255,255,0.82)",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 5,
  },
  polaroidSelected: {
    borderColor: "#ffaa00",
    shadowColor: "#ffaa00",
    shadowOpacity: 0.55,
    shadowRadius: 5,
    elevation: 7,
  },
  polaroidPhoto: {
    width: "100%",
    height: 48,
    overflow: "hidden",
  },
  polaroidPhotoHighlight: {
    width: "72%",
    height: "120%",
    alignSelf: "center",
    backgroundColor: "rgba(255,255,255,0.09)",
    transform: [{ rotate: "24deg" }],
  },
  polaroidCaption: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 2,
  },
  polaroidName: {
    color: "#25231f",
    fontSize: 10,
    fontWeight: "600",
    textAlign: "center",
    width: "100%",
  },
  polaroidNameSelected: {
    color: "#9a5700",
    fontWeight: "800",
  },
  filmStrip: {
    width: 54,
    height: 22,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 2,
    paddingHorizontal: 2,
    paddingVertical: 2,
    backgroundColor: "#151515",
    borderRadius: 3,
    borderWidth: 1,
    borderColor: "#303030",
    marginBottom: 2,
    overflow: "hidden",
  },
  effectPreviewSelected: {
    borderColor: "rgba(255,170,0,0.65)",
  },
  filmPerforations: {
    height: "100%",
    justifyContent: "space-between",
  },
  filmPerforation: {
    width: 3,
    height: 3,
    borderRadius: 1,
    backgroundColor: "#c7bda3",
    opacity: 0.42,
  },
  grainSample: {
    flex: 1,
    height: "100%",
    position: "relative",
    overflow: "hidden",
  },
  grainDot: {
    position: "absolute",
    borderRadius: 2,
    backgroundColor: "rgba(255,255,255,0.46)",
  },
  halationLens: {
    width: 54,
    height: 22,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#08090b",
    borderRadius: 11,
    borderWidth: 1,
    borderColor: "#303030",
    marginBottom: 2,
    overflow: "hidden",
  },
  halationSample: {
    width: 36,
    height: 4,
    borderRadius: 7,
    opacity: 0.82,
  },
  effectName: {
    color: "#777",
    fontSize: 9,
    textAlign: "center",
    maxWidth: 58,
  },
  effectNameSelected: {
    color: "#c8953e",
    fontWeight: "600",
  },
});
