import { StyleSheet } from "react-native";

export default StyleSheet.create({
  container: { position: "absolute", bottom: -30, left: 10, right: 10, flexDirection: "row", alignItems: "flex-end", gap: 8 },
  panel: {
    flex: 1,
    minWidth: 0,
    paddingTop: 10,
    paddingBottom: 10,
    overflow: "hidden",
  },
  panelHeader: { minHeight: 34, paddingHorizontal: 6, marginBottom: 10, flexDirection: "row", alignItems: "center", justifyContent: "space-between" },
  panelTitle: { color: "#f6f6f4", fontSize: 16, fontWeight: "700", letterSpacing: -0.2, textShadowColor: "rgba(0,0,0,0.9)", textShadowOffset: { width: 0, height: 1 }, textShadowRadius: 4 },
  activeEffectsBadge: { flexDirection: "row", alignItems: "center", gap: 5, paddingHorizontal: 8, height: 24, borderRadius: 12, backgroundColor: "rgba(12,12,12,0.42)", borderWidth: 1, borderColor: "rgba(255,170,0,0.28)" },
  activeEffectsDot: { width: 5, height: 5, borderRadius: 3, backgroundColor: "#ffaa00" },
  activeEffectsText: { color: "#dba747", fontSize: 9, fontWeight: "700" },
  tabBar: { marginHorizontal: 0, marginBottom: 12, height: 40, padding: 3, borderRadius: 10, flexDirection: "row", gap: 3 },
  tab: { flex: 1, minWidth: 0, borderRadius: 7, flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 5 },
  tabActive: { backgroundColor: "rgba(12,12,12,0.46)", borderWidth: 1, borderColor: "rgba(255,170,0,0.38)" },
  tabLabel: { color: "rgba(255,255,255,0.68)", fontSize: 10, fontWeight: "600", textShadowColor: "rgba(0,0,0,0.9)", textShadowOffset: { width: 0, height: 1 }, textShadowRadius: 3 },
  tabLabelActive: { color: "#ffaa00", fontWeight: "700" },
  tabStatusDot: { width: 4, height: 4, borderRadius: 2, backgroundColor: "#ffaa00", marginLeft: -2 },
  optionsContent: { paddingHorizontal: 0, gap: 7 },
  optionCard: { width: 72, padding: 4, paddingBottom: 7, borderRadius: 10, borderWidth: 1, borderColor: "transparent" },
  optionCardSelected: { borderColor: "rgba(255,170,0,0.72)", backgroundColor: "rgba(12,12,12,0.34)" },
  previewFrame: { position: "relative", width: "100%", height: 58, borderRadius: 8, overflow: "hidden", backgroundColor: "#242424" },
  preview: { flex: 1, alignItems: "center", justifyContent: "center", overflow: "hidden" },
  previewSheen: { position: "absolute", width: 20, height: 78, backgroundColor: "rgba(255,255,255,0.09)", transform: [{ rotate: "22deg" }] },
  selectedMark: { position: "absolute", top: 4, right: 4, width: 17, height: 17, borderRadius: 9, alignItems: "center", justifyContent: "center", backgroundColor: "#ffaa00", borderWidth: 1, borderColor: "rgba(0,0,0,0.25)" },
  optionName: { color: "rgba(255,255,255,0.72)", fontSize: 10, fontWeight: "600", textAlign: "center", marginTop: 6, textShadowColor: "rgba(0,0,0,0.95)", textShadowOffset: { width: 0, height: 1 }, textShadowRadius: 3 },
  optionNameSelected: { color: "#ffaa00", fontWeight: "700" },
  halationPreview: { backgroundColor: "#171717" },
  halationGlow: { position: "absolute", left: 8, right: 8, height: 12, borderRadius: 8, opacity: 0.9 },
  shutterDivider: {
    width: 1,
    alignSelf: "stretch",
    marginVertical: 16,
    backgroundColor: "rgba(255,255,255,0.16)",
  },
  quickShutterSlot: {
    width: 62,
    alignSelf: "stretch",
    alignItems: "center",
    justifyContent: "center",
  },
});
