import { StyleSheet } from "react-native";

export default StyleSheet.create({
  container: { flex: 1, backgroundColor: "#000" },
  loadingContainer: { flex: 1, alignItems: "center", justifyContent: "center", backgroundColor: "#000" },
  loadingText: { color: "#a0a0a0", fontSize: 14, marginTop: 12 },
  header: { height: 58, flexDirection: "row", alignItems: "center", paddingHorizontal: 10, borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: "#242424" },
  headerButton: { width: 44, height: 44, alignItems: "center", justifyContent: "center" },
  headerTitle: { flex: 1, color: "#fff", fontSize: 18, fontWeight: "700", textAlign: "center" },
  scrollView: { flex: 1 },
  scrollContent: { paddingHorizontal: 18, paddingTop: 20, paddingBottom: 44 },
  intro: { color: "#8f8f8f", fontSize: 14, lineHeight: 20, marginBottom: 24, paddingHorizontal: 2 },
  section: { marginBottom: 26 },
  sectionTitle: { color: "#aaa", fontSize: 12, fontWeight: "700", letterSpacing: 0.8, marginBottom: 9, paddingHorizontal: 4, textTransform: "uppercase" },
  sectionDescription: { color: "#777", fontSize: 13, lineHeight: 18, marginBottom: 11, marginTop: -3, paddingHorizontal: 4 },
  group: { backgroundColor: "#111", borderColor: "#252525", borderRadius: 14, borderWidth: 1, overflow: "hidden" },
  menuRow: { minHeight: 68, flexDirection: "row", alignItems: "center", paddingHorizontal: 14, paddingVertical: 12, borderBottomColor: "#252525", borderBottomWidth: StyleSheet.hairlineWidth },
  actionRow: { minHeight: 58, flexDirection: "row", alignItems: "center", paddingHorizontal: 15, paddingVertical: 11, borderBottomColor: "#252525", borderBottomWidth: StyleSheet.hairlineWidth },
  rowPressed: { backgroundColor: "#1a1a1a" },
  menuIcon: { width: 38, height: 38, borderRadius: 11, alignItems: "center", justifyContent: "center", backgroundColor: "rgba(255, 170, 0, 0.1)", marginRight: 12 },
  actionIcon: { width: 28, marginRight: 7 },
  menuText: { flex: 1 },
  rowLabel: { color: "#f4f4f4", fontSize: 15, fontWeight: "600" },
  rowDescription: { color: "#858585", fontSize: 12, lineHeight: 17, marginTop: 3 },
  rowStatus: { color: "#9b9b9b", fontSize: 12, marginHorizontal: 8 },
  modelCard: { backgroundColor: "#111", borderColor: "#252525", borderRadius: 14, borderWidth: 1, padding: 16 },
  modelHeader: { flexDirection: "row", alignItems: "center" },
  modelStatus: { color: "#ffaa00", fontSize: 13, fontWeight: "600", marginTop: 15 },
  modelError: { color: "#ff8585", fontSize: 12, lineHeight: 17, marginTop: 8 },
  progressTrack: { height: 4, backgroundColor: "#303030", borderRadius: 2, marginTop: 10, overflow: "hidden" },
  progressFill: { height: "100%", backgroundColor: "#ffaa00" },
  modelActions: { flexDirection: "row", marginTop: 16 },
  primaryButton: { backgroundColor: "#ffaa00", borderRadius: 10, paddingHorizontal: 15, paddingVertical: 11 },
  primaryButtonText: { color: "#171000", fontSize: 13, fontWeight: "700" },
  secondaryButton: { borderColor: "#444", borderRadius: 10, borderWidth: 1, paddingHorizontal: 15, paddingVertical: 10 },
  secondaryButtonText: { color: "#ddd", fontSize: 13, fontWeight: "600" },
  controlRow: { minHeight: 57, flexDirection: "row", alignItems: "center", paddingLeft: 12, paddingRight: 6, borderBottomColor: "#252525", borderBottomWidth: StyleSheet.hairlineWidth },
  controlIndex: { width: 26, height: 26, borderRadius: 8, alignItems: "center", justifyContent: "center", backgroundColor: "#202020", marginRight: 10 },
  controlIndexText: { color: "#9d9d9d", fontSize: 12, fontWeight: "700" },
  controlName: { flex: 1, color: "#f0f0f0", fontSize: 14, fontWeight: "500" },
  iconButton: { width: 35, height: 40, alignItems: "center", justifyContent: "center" },
  availableRow: { minHeight: 55, flexDirection: "row", alignItems: "center", paddingHorizontal: 14, borderBottomColor: "#252525", borderBottomWidth: StyleSheet.hairlineWidth },
  availableName: { flex: 1, color: "#e5e5e5", fontSize: 14, marginLeft: 12 },
  importButton: { height: 48, flexDirection: "row", alignItems: "center", justifyContent: "center", backgroundColor: "#ffaa00", borderRadius: 12, marginBottom: 28 },
  importButtonText: { color: "#171000", fontSize: 15, fontWeight: "700", marginLeft: 9 },
  lutList: { backgroundColor: "#111", borderColor: "#252525", borderRadius: 14, borderWidth: 1, padding: 10 },
  emptyState: { alignItems: "center", backgroundColor: "#111", borderColor: "#252525", borderRadius: 14, borderWidth: 1, paddingHorizontal: 20, paddingVertical: 34 },
  emptyTitle: { color: "#d8d8d8", fontSize: 15, fontWeight: "600", marginTop: 10 },
  emptyDescription: { color: "#777", fontSize: 12, marginTop: 5, textAlign: "center" },
  socialRow: { flexDirection: "row", justifyContent: "center", marginTop: -4 },
  socialButton: { width: 44, height: 44, borderRadius: 22, alignItems: "center", justifyContent: "center", backgroundColor: "#151515", borderColor: "#292929", borderWidth: 1, marginHorizontal: 5 },
  version: { color: "#555", fontSize: 11, marginTop: 16, textAlign: "center" },
});
