import { StyleSheet } from "react-native";

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#000",
  },
  slide: {
    flex: 1,
    backgroundColor: "#000",
  },
  slideBackground: {
    flex: 1,
  },
  chrome: {
    ...StyleSheet.absoluteFillObject,
    justifyContent: "space-between",
  },
  headerShade: {
    position: "absolute",
    top: 0,
    right: 0,
    left: 0,
    height: 132,
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 24,
  },
  brand: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  brandIcon: {
    width: 30,
    height: 30,
    borderRadius: 8,
  },
  brandName: {
    color: "#fff",
    fontSize: 12,
    fontWeight: "800",
    letterSpacing: 2.2,
  },
  skipButton: {
    minHeight: 40,
    justifyContent: "center",
    paddingHorizontal: 4,
  },
  skipText: {
    color: "rgba(255, 255, 255, 0.82)",
    fontSize: 14,
    fontWeight: "600",
  },
  visualArea: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    paddingTop: 86,
    paddingHorizontal: 24,
  },
  copyBlock: {
    minHeight: 285,
    justifyContent: "flex-start",
    paddingHorizontal: 28,
    paddingTop: 20,
    paddingBottom: 148,
  },
  eyebrow: {
    marginBottom: 12,
    color: "#ffb21d",
    fontSize: 11,
    fontWeight: "800",
    letterSpacing: 2.1,
  },
  title: {
    maxWidth: 390,
    color: "#fff",
    fontSize: 38,
    fontWeight: "700",
    letterSpacing: -1.35,
    lineHeight: 42,
  },
  description: {
    maxWidth: 370,
    marginTop: 14,
    color: "rgba(255, 255, 255, 0.68)",
    fontSize: 16,
    lineHeight: 23,
  },
  footer: {
    paddingHorizontal: 24,
  },
  footerShade: {
    position: "absolute",
    right: 0,
    bottom: -60,
    left: 0,
    height: 220,
  },
  pagination: {
    flexDirection: "row",
    alignItems: "center",
    gap: 7,
    marginBottom: 18,
  },
  paginationDot: {
    width: 7,
    height: 7,
    borderRadius: 4,
    backgroundColor: "rgba(255, 255, 255, 0.28)",
  },
  paginationDotActive: {
    width: 26,
    backgroundColor: "#ffb21d",
  },
  actions: {
    flexDirection: "row",
    gap: 12,
  },
  backButton: {
    width: 56,
    height: 56,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.2)",
    borderRadius: 18,
    backgroundColor: "rgba(255, 255, 255, 0.08)",
  },
  primaryButton: {
    flex: 1,
    height: 56,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 10,
    borderRadius: 18,
    backgroundColor: "#ffb21d",
  },
  primaryButtonFull: {
    flex: 1,
  },
  primaryButtonText: {
    color: "#111",
    fontSize: 16,
    fontWeight: "800",
  },
  buttonPressed: {
    opacity: 0.64,
  },
  primaryButtonPressed: {
    opacity: 0.82,
    transform: [{ scale: 0.985 }],
  },
  mockupFrame: {
    width: "100%",
    maxWidth: 440,
    aspectRatio: 1.12,
    overflow: "hidden",
    borderWidth: 1,
    borderColor: "rgba(255, 178, 29, 0.24)",
    borderRadius: 30,
    backgroundColor: "#f29908",
    shadowColor: "#ff9700",
    shadowOffset: { width: 0, height: 20 },
    shadowOpacity: 0.2,
    shadowRadius: 36,
    elevation: 9,
  },
  mockupImage: {
    width: "100%",
    height: "100%",
  },
  mockupShade: {
    ...StyleSheet.absoluteFillObject,
  },
  controlBadge: {
    position: "absolute",
    right: 14,
    bottom: 14,
    flexDirection: "row",
    alignItems: "center",
    gap: 7,
    paddingHorizontal: 12,
    paddingVertical: 9,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.12)",
    borderRadius: 999,
    backgroundColor: "rgba(0, 0, 0, 0.76)",
  },
  controlBadgeText: {
    color: "#fff",
    fontSize: 9,
    fontWeight: "800",
    letterSpacing: 1.2,
  },
  styleStage: {
    width: "100%",
    maxWidth: 380,
    alignItems: "center",
  },
  photoCard: {
    width: "76%",
    aspectRatio: 0.83,
    overflow: "hidden",
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.14)",
    borderRadius: 28,
    backgroundColor: "#171717",
    shadowColor: "#ffb21d",
    shadowOffset: { width: 0, height: 18 },
    shadowOpacity: 0.14,
    shadowRadius: 32,
    elevation: 8,
  },
  stylePhoto: {
    width: "100%",
    height: "100%",
  },
  photoShade: {
    ...StyleSheet.absoluteFillObject,
  },
  photoMeta: {
    position: "absolute",
    right: 18,
    bottom: 16,
    left: 18,
  },
  photoMetaLabel: {
    marginBottom: 3,
    color: "#ffb21d",
    fontSize: 9,
    fontWeight: "800",
    letterSpacing: 1.7,
  },
  photoMetaValue: {
    color: "#fff",
    fontSize: 15,
    fontWeight: "700",
  },
  presetRail: {
    flexDirection: "row",
    gap: 8,
    marginTop: -16,
    padding: 8,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.1)",
    borderRadius: 18,
    backgroundColor: "rgba(17, 17, 17, 0.96)",
  },
  presetChip: {
    alignItems: "center",
    gap: 6,
    paddingHorizontal: 10,
    paddingVertical: 9,
    borderRadius: 12,
  },
  presetChipActive: {
    backgroundColor: "rgba(255, 178, 29, 0.14)",
  },
  presetColor: {
    width: 24,
    height: 24,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.2)",
    borderRadius: 8,
  },
  presetText: {
    color: "rgba(255, 255, 255, 0.52)",
    fontSize: 8,
    fontWeight: "800",
    letterSpacing: 0.55,
  },
  presetTextActive: {
    color: "#ffb21d",
  },
  readyStage: {
    width: "100%",
    alignItems: "center",
  },
  iconGlowOuter: {
    width: 210,
    height: 210,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "rgba(255, 178, 29, 0.08)",
    borderRadius: 105,
    backgroundColor: "rgba(255, 178, 29, 0.025)",
  },
  iconGlowInner: {
    width: 152,
    height: 152,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "rgba(255, 178, 29, 0.14)",
    borderRadius: 76,
    backgroundColor: "rgba(255, 178, 29, 0.06)",
    shadowColor: "#ff9d00",
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.28,
    shadowRadius: 38,
    elevation: 8,
  },
  readyIcon: {
    width: 104,
    height: 104,
    borderRadius: 27,
  },
  featureRow: {
    flexDirection: "row",
    gap: 9,
    marginTop: 30,
  },
  featureItem: {
    minWidth: 96,
    alignItems: "center",
    gap: 7,
    paddingHorizontal: 10,
    paddingVertical: 13,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.08)",
    borderRadius: 17,
    backgroundColor: "rgba(255, 255, 255, 0.04)",
  },
  featureLabel: {
    color: "rgba(255, 255, 255, 0.7)",
    fontSize: 11,
    fontWeight: "600",
  },
});
