import { StyleSheet } from "react-native";

export default StyleSheet.create({
  reorderHint: { color: "#98989f", fontSize: 13, marginBottom: 12 },
  container: {
    flex: 1,
    backgroundColor: "#000",
  },
  animatedContent: {
    flex: 1,
  },
  slide: {
    flex: 1,
    backgroundColor: "#000",
  },
  customizerTitle: {
    fontSize: 32,
    lineHeight: 37,
  },
  customizerScroll: {
    marginTop: 24,
  },
  customizerScrollContent: {
    paddingHorizontal: 28,
    paddingBottom: 8,
  },
  viewfinderPreview: {
    width: "100%",
    maxWidth: 430,
    aspectRatio: 1.8,
    alignSelf: "center",
    overflow: "hidden",
    borderWidth: 1,
    borderColor: "rgba(255, 170, 0, 0.28)",
    borderRadius: 22,
    backgroundColor: "#151515",
  },
  viewfinderPhoto: {
    width: "100%",
    height: "100%",
  },
  viewfinderShade: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "rgba(0, 0, 0, 0.12)",
  },
  previewGrid: {
    ...StyleSheet.absoluteFillObject,
  },
  previewGridLineV: {
    position: "absolute",
    top: 0,
    bottom: 0,
    width: StyleSheet.hairlineWidth,
    backgroundColor: "rgba(255, 255, 255, 0.62)",
  },
  previewGridLineH: {
    position: "absolute",
    right: 0,
    left: 0,
    height: StyleSheet.hairlineWidth,
    backgroundColor: "rgba(255, 255, 255, 0.62)",
  },
  previewLevel: {
    position: "absolute",
    top: "50%",
    left: "50%",
    width: 88,
    height: 20,
    alignItems: "center",
    justifyContent: "center",
    transform: [{ translateX: -44 }, { translateY: -10 }],
  },
  previewLevelLine: {
    width: 88,
    height: 2,
    borderRadius: 1,
    backgroundColor: "#ffaa00",
  },
  previewLevelDot: {
    position: "absolute",
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: "#ffaa00",
  },
  previewHistogram: {
    position: "absolute",
    right: 10,
    bottom: 10,
    height: 42,
    flexDirection: "row",
    alignItems: "flex-end",
    gap: 2,
    paddingHorizontal: 7,
    paddingVertical: 5,
    borderRadius: 8,
    backgroundColor: "rgba(0, 0, 0, 0.62)",
  },
  previewHistogramBar: {
    width: 3,
    borderRadius: 2,
    backgroundColor: "rgba(255, 170, 0, 0.88)",
  },
  previewControls: {
    position: "absolute",
    left: 10,
    flexDirection: "row",
    gap: 10,
    paddingHorizontal: 10,
    paddingVertical: 7,
    borderRadius: 10,
    backgroundColor: "rgba(0, 0, 0, 0.62)",
  },
  previewControlsTop: {
    top: 10,
  },
  previewControlsBottom: {
    bottom: 10,
  },
  toggleList: {
    maxWidth: 430,
    width: "100%",
    alignSelf: "center",
    marginTop: 12,
  },
  controlsContent: {
    marginTop: 24,
    paddingHorizontal: 28,
    width: "100%",
    maxWidth: 560,
    alignSelf: "center",
  },
  presetList: { gap: 10 },
  presetCard: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    minHeight: 68,
    padding: 16,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "#2b2926",
    backgroundColor: "#111",
  },
  presetCardActive: {
    borderColor: "#ffaa00",
    backgroundColor: "rgba(255, 170, 0, 0.08)",
  },
  presetTitle: { flex: 1, color: "#e1dacf", fontSize: 14, lineHeight: 20, fontWeight: "500" },
  presetTitleActive: { color: "#fff" },
  presetSummary: { marginTop: 8, gap: 12, marginBottom: 8 },
  presetControlNames: { color: "#a5a39f", fontSize: 12, lineHeight: 18 },
  presetIconRow: { flexDirection: "row", flexWrap: "wrap", gap: 8, paddingTop: 4 },
  presetControlIcon: {
    width: 38,
    height: 38,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 12,
    backgroundColor: "rgba(255, 170, 0, 0.08)",
  },
  personalizeCard: {
    minHeight: 60,
    marginTop: 8,
    backgroundColor: "#080808",
    borderColor: "#252320",
  },
  personalizeCardActive: {
    borderColor: "rgba(255, 170, 0, 0.5)",
    backgroundColor: "rgba(255, 170, 0, 0.04)",
  },
  personalizeText: { flex: 1, color: "#a5a39f", fontSize: 13, lineHeight: 19, fontWeight: "500" },
  topBarEditorContent: { paddingBottom: 8 },
  controlsNote: {
    marginTop: 12,
    color: "#93908b",
    fontSize: 12,
    lineHeight: 18,
  },
  topBarCountRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-end",
    marginBottom: 9,
  },
  topBarCount: {
    color: "#ffaa00",
    fontSize: 12,
    fontWeight: "800",
  },
  availableLabel: {
    marginTop: 20,
    marginBottom: 10,
    color: "rgba(255, 255, 255, 0.48)",
    fontSize: 10,
    fontWeight: "800",
    letterSpacing: 1.5,
  },
  availableControls: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  availableControl: {
    flexDirection: "row",
    alignItems: "center",
    gap: 7,
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderWidth: 1,
    borderColor: "rgba(255, 170, 0, 0.22)",
    borderRadius: 13,
    backgroundColor: "rgba(255, 170, 0, 0.07)",
  },
  availableControlDisabled: {
    opacity: 0.3,
  },
  availableControlText: {
    color: "rgba(255, 255, 255, 0.84)",
    fontSize: 12,
    fontWeight: "600",
  },
  permissionsScrollContent: {
    paddingHorizontal: 28,
    paddingBottom: 8,
  },
  permissionList: {
    width: "100%",
    maxWidth: 460,
    alignSelf: "center",
    gap: 10,
  },
  permissionCard: {
    minHeight: 88,
    flexDirection: "row",
    alignItems: "center",
    gap: 13,
    padding: 15,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.1)",
    borderRadius: 18,
    backgroundColor: "rgba(255, 255, 255, 0.04)",
  },
  permissionCardGranted: {
    borderColor: "rgba(255, 170, 0, 0.3)",
    backgroundColor: "rgba(255, 170, 0, 0.08)",
  },
  permissionIcon: {
    width: 44,
    height: 44,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 14,
    backgroundColor: "rgba(255, 170, 0, 0.12)",
  },
  permissionIconGranted: {
    backgroundColor: "#ffaa00",
  },
  permissionCopy: {
    flex: 1,
  },
  permissionCardTitle: {
    color: "#fff",
    fontSize: 15,
    fontWeight: "700",
  },
  permissionCardDescription: {
    marginTop: 5,
    color: "rgba(255, 255, 255, 0.62)",
    fontSize: 12,
    lineHeight: 17,
  },
  permissionStatus: {
    flexShrink: 0,
    color: "#ffaa00",
    fontSize: 11,
    fontWeight: "700",
  },
  permissionStatusGranted: {
    color: "#ffaa00",
  },
  permissionsNote: {
    width: "100%",
    maxWidth: 460,
    alignSelf: "center",
    marginTop: 14,
    color: "rgba(255, 255, 255, 0.42)",
    fontSize: 11,
    lineHeight: 16,
    textAlign: "center",
  },
  chrome: {
    ...StyleSheet.absoluteFillObject,
    justifyContent: "space-between",
  },
  headerShade: {
    position: "absolute",
    top: 0,
    right: 0,
    left: 0,
    height: 132,
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 24,
  },
  brand: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  brandIcon: {
    width: 30,
    height: 30,
    borderRadius: 8,
  },
  brandName: {
    color: "#fff",
    fontSize: 12,
    fontWeight: "800",
    letterSpacing: 2.2,
  },
  skipButton: {
    minHeight: 40,
    justifyContent: "center",
    paddingHorizontal: 4,
  },
  skipText: {
    color: "rgba(255, 255, 255, 0.82)",
    fontSize: 14,
    fontWeight: "600",
  },
  copyBlock: {
    paddingHorizontal: 28,
    paddingTop: 12,
    maxWidth: 560,
    width: "100%",
    alignSelf: "center",
  },
  title: {
    color: "#f5f3ee",
    fontSize: 42,
    fontWeight: "500",
    letterSpacing: -1.8,
    lineHeight: 46,
  },
  description: {
    marginTop: 16,
    color: "#a5a39f",
    fontSize: 15,
    lineHeight: 23,
    maxWidth: 420,
  },
  footer: {
    backgroundColor: "#000",
    paddingTop: 12,
    paddingHorizontal: 28,
    width: "100%",
    maxWidth: 560,
    alignSelf: "center",
  },
  footerShade: {
    position: "absolute",
    right: -28,
    bottom: -60,
    left: -28,
    height: 220,
  },
  pagination: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  paginationDot: {
    width: 14,
    height: 3,
    borderRadius: 2,
    backgroundColor: "#393733",
  },
  paginationDotActive: {
    width: 28,
    backgroundColor: "#ffaa00",
  },
  actions: {
    flexDirection: "row",
    gap: 12,
  },
  backButton: {
    width: 56,
    height: 56,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "#35332f",
    borderRadius: 28,
    backgroundColor: "#111",
  },
  primaryButton: {
    flex: 1,
    minHeight: 56,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 10,
    borderRadius: 999,
    backgroundColor: "#ffaa00",
  },
  primaryButtonFull: {
    flex: 1,
  },
  primaryButtonText: {
    color: "#171000",
    fontSize: 15,
    fontWeight: "600",
  },
  buttonPressed: {
    opacity: 0.64,
  },
  primaryButtonPressed: {
    opacity: 0.82,
    transform: [{ scale: 0.985 }],
  },
  pageContent: { flexGrow: 1 },
  hero: { width: "100%", overflow: "hidden" },
  heroPhoto: { width: "100%", height: "100%", resizeMode: "cover" },
  heroShade: { ...StyleSheet.absoluteFillObject },
  photoTriptych: { flex: 1, flexDirection: "row", gap: 10, paddingTop: 100, paddingBottom: 25, transform: [{ rotate: "-6deg" }], marginHorizontal: -40 },
  triptychPhoto: { flex: 1, height: "85%", borderRadius: 6, marginTop: 25 },
  triptychCenter: { flex: 1.5, height: "100%", marginTop: 0 },
  progressRow: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", marginBottom: 20 },
  stepCount: { color: "#e1dacf", fontSize: 11, fontVariant: ["tabular-nums"], letterSpacing: 1 },
  stepCountMuted: { color: "#77726a" },
  betaContent: { marginTop: 28, paddingHorizontal: 28, width: "100%", maxWidth: 560, alignSelf: "center" },
  feedbackCard: { flexDirection: "row", alignItems: "center", gap: 18, paddingBottom: 24, marginBottom: 28, borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: "#35312a" },
  feedbackArrow: { transform: [{ rotate: "-45deg" }] },
  feedbackCopy: { flex: 1 },
  feedbackTitle: { color: "#fff", fontSize: 16, fontWeight: "500", letterSpacing: 0.1, marginBottom: 4 },
  feedbackDescription: { color: "#a9a9a9", fontSize: 12, lineHeight: 17 },
  betaToggle: { paddingHorizontal: 0 },
  betaNote: { color: "#93908b", fontSize: 12, lineHeight: 19, marginTop: 16 },
});
