//! Generate content-neutral monochrome HEVC for supported capture ratios.
//! Verify every encoded frame decodes to zero before emitting Rust constants.
use std::{
    fmt::Write,
    io::Write as IoWrite,
    process::{Command, Stdio},
};
use xdremux_core::hevc;
fn main() {
    let mut source=String::from("// Generated by examples/generate_semantic_matte_templates.rs.\n// All five HEVC frames decode to gray8=0; no reference-photo pixels are used.\npub fn get(width:u32,height:u32)->Option<(&'static [u8], &'static [u8])> {\n    match (width,height) {\n");
    for (w, h) in [(768, 576), (576, 768), (768, 432), (432, 768), (768, 768)] {
        let pixels = vec![0u8; (w * h) as usize];
        let streams = hevc::x265_encode_tiles(&[&pixels], w, h, 1, false).unwrap();
        let annex = &streams[0];
        let mut decoder = Command::new("ffmpeg")
            .args([
                "-v",
                "error",
                "-f",
                "hevc",
                "-i",
                "pipe:0",
                "-frames:v",
                "1",
                "-f",
                "rawvideo",
                "-pix_fmt",
                "gray",
                "pipe:1",
            ])
            .stdin(Stdio::piped())
            .stdout(Stdio::piped())
            .spawn()
            .unwrap();
        decoder.stdin.take().unwrap().write_all(annex).unwrap();
        let decoded = decoder.wait_with_output().unwrap();
        assert!(decoded.status.success());
        assert_eq!(decoded.stdout.len(), pixels.len());
        assert!(decoded.stdout.iter().all(|p| *p == 0));
        let hvcc = hevc::extract_hvcc_config_with_chroma(annex, 0).unwrap();
        assert_eq!(hvcc[16] & 3, 0);
        let stream = hevc::hevc_byte_stream_to_length_prefixed(&hevc::drop_parameter_nals(annex));
        writeln!(
            source,
            "        ({w},{h}) => Some((&{stream:?}, &{hvcc:?})),"
        )
        .unwrap();
    }
    source.push_str("        _ => None,\n    }\n}\n");
    std::fs::write(std::env::args().nth(1).expect("pass output .rs"), source).unwrap();
    println!("Five monochrome matte templates verified by decoding every pixel.");
}
